### ISSUE TITLE
Metabase connection to DB

### ISSUE THREAD

**Issue by ervinebalo** [Cambalab/metabase-compose#1]
Hi there, first of all, thanks very much for sharing this. Super helpful. 

I do have question. Upon initial set up of Metabase, it asks for the database connection. 

I am getting the following error
Database name : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

I have set `localhost` and `5432` for host and port. Would the values be something else?

Thanks!

**Comment by sgobotta** [comment]
Hello @ervinebalo, thanks for sharing. We're grateful this is motivating people to use metabase under a docker environment.

I might get an idea about the issue. Could you please tell us a little bit about it?

+ Paste the output of the error
+ have you edited the `docker-compose.yml` file in some way?

Thanks!

**Comment by ervinebalo** [comment]
Hi @sgobotta,

- I have not edited the `docker-compose.yml` file. 
- I have created an `.env` file and modified that with my info.
- Running `docker-compose build` and `docker-compose up` works just fine
- When I launch `localhost:3000` I am taken to the metabase initial setup screens
- On that setup screen Step 3, I use `PostgreSQL`, `localhost`, and '5432` as values for Type, Host, and Port.
- I get an error on the form that says `Database name : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.`

So the error is in Metabase itself, not docker.

**Comment by sgobotta** [comment]
> Hi @sgobotta,
> 
> * I have not edited the `docker-compose.yml` file.
> * I have created an `.env` file and modified that with my info.
> * Running `docker-compose build` and `docker-compose up` works just fine
> * When I launch `localhost:3000` I am taken to the metabase initial setup screens
> * On that setup screen Step 3, I use `PostgreSQL`, `localhost`, and '5432` as values for Type, Host, and Port.
> * I get an error on the form that says `Database name : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.`
> 
> So the error is in Metabase itself, not docker.

Oh, ok. Could you try using `db` instead of `localhost` on step 3. Please let me know if that worked.

**Comment by ervinebalo** [comment]
`db` for host works! Thanks

**Comment by sgobotta** [comment]
> `db` for host works! Thanks

Nice. Just for the record, whenever you run services from a dockerized environment, you should use the [service name](https://github.com/Cambalab/metabase-compose/blob/main/docker-compose.yml#L4) as the host value.
